//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSRP.TSHSRPService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TSHSRPService.HSRPAuthorizationServiceSoap")]
    public interface HSRPAuthorizationServiceSoap {
        
        // CODEGEN: Generating message contract since element name fromdate from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHSRPAuthorizationDetails", ReplyAction="*")]
        HSRP.TSHSRPService.GetHSRPAuthorizationDetailsResponse GetHSRPAuthorizationDetails(HSRP.TSHSRPService.GetHSRPAuthorizationDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHSRPAuthorizationno", ReplyAction="*")]
        HSRP.TSHSRPService.GetHSRPAuthorizationnoResponse GetHSRPAuthorizationno(HSRP.TSHSRPService.GetHSRPAuthorizationnoRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPCharges", ReplyAction="*")]
        HSRP.TSHSRPService.UpdateHSRPChargesResponse UpdateHSRPCharges(HSRP.TSHSRPService.UpdateHSRPChargesRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPLaserCodes", ReplyAction="*")]
        HSRP.TSHSRPService.UpdateHSRPLaserCodesResponse UpdateHSRPLaserCodes(HSRP.TSHSRPService.UpdateHSRPLaserCodesRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPAffixation", ReplyAction="*")]
        HSRP.TSHSRPService.UpdateHSRPAffixationResponse UpdateHSRPAffixation(HSRP.TSHSRPService.UpdateHSRPAffixationRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPAvailableAtOffice", ReplyAction="*")]
        HSRP.TSHSRPService.UpdateHSRPAvailableAtOfficeResponse UpdateHSRPAvailableAtOffice(HSRP.TSHSRPService.UpdateHSRPAvailableAtOfficeRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRegnOnAuthorizationDate", ReplyAction="*")]
        HSRP.TSHSRPService.UpdateRegnOnAuthorizationDateResponse UpdateRegnOnAuthorizationDate(HSRP.TSHSRPService.UpdateRegnOnAuthorizationDateRequest request);
        
        // CODEGEN: Generating message contract since element name fromdate from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAuthorizationnotRegistered", ReplyAction="*")]
        HSRP.TSHSRPService.GetAuthorizationnotRegisteredResponse GetAuthorizationnotRegistered(HSRP.TSHSRPService.GetAuthorizationnotRegisteredRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHSRPAuthorizationDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHSRPAuthorizationDetails", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.GetHSRPAuthorizationDetailsRequestBody Body;
        
        public GetHSRPAuthorizationDetailsRequest() {
        }
        
        public GetHSRPAuthorizationDetailsRequest(HSRP.TSHSRPService.GetHSRPAuthorizationDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHSRPAuthorizationDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fromdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string todate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string officecode;
        
        public GetHSRPAuthorizationDetailsRequestBody() {
        }
        
        public GetHSRPAuthorizationDetailsRequestBody(string fromdate, string todate, string officecode) {
            this.fromdate = fromdate;
            this.todate = todate;
            this.officecode = officecode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHSRPAuthorizationDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHSRPAuthorizationDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.GetHSRPAuthorizationDetailsResponseBody Body;
        
        public GetHSRPAuthorizationDetailsResponse() {
        }
        
        public GetHSRPAuthorizationDetailsResponse(HSRP.TSHSRPService.GetHSRPAuthorizationDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHSRPAuthorizationDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHSRPAuthorizationDetailsResult;
        
        public GetHSRPAuthorizationDetailsResponseBody() {
        }
        
        public GetHSRPAuthorizationDetailsResponseBody(string GetHSRPAuthorizationDetailsResult) {
            this.GetHSRPAuthorizationDetailsResult = GetHSRPAuthorizationDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHSRPAuthorizationnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHSRPAuthorizationno", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.GetHSRPAuthorizationnoRequestBody Body;
        
        public GetHSRPAuthorizationnoRequest() {
        }
        
        public GetHSRPAuthorizationnoRequest(HSRP.TSHSRPService.GetHSRPAuthorizationnoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHSRPAuthorizationnoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        public GetHSRPAuthorizationnoRequestBody() {
        }
        
        public GetHSRPAuthorizationnoRequestBody(string Authno) {
            this.Authno = Authno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHSRPAuthorizationnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHSRPAuthorizationnoResponse", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.GetHSRPAuthorizationnoResponseBody Body;
        
        public GetHSRPAuthorizationnoResponse() {
        }
        
        public GetHSRPAuthorizationnoResponse(HSRP.TSHSRPService.GetHSRPAuthorizationnoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHSRPAuthorizationnoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHSRPAuthorizationnoResult;
        
        public GetHSRPAuthorizationnoResponseBody() {
        }
        
        public GetHSRPAuthorizationnoResponseBody(string GetHSRPAuthorizationnoResult) {
            this.GetHSRPAuthorizationnoResult = GetHSRPAuthorizationnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPChargesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPCharges", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.UpdateHSRPChargesRequestBody Body;
        
        public UpdateHSRPChargesRequest() {
        }
        
        public UpdateHSRPChargesRequest(HSRP.TSHSRPService.UpdateHSRPChargesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPChargesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CollectionDate;
        
        public UpdateHSRPChargesRequestBody() {
        }
        
        public UpdateHSRPChargesRequestBody(string Authno, decimal Amount, string CollectionDate) {
            this.Authno = Authno;
            this.Amount = Amount;
            this.CollectionDate = CollectionDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPChargesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPChargesResponse", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.UpdateHSRPChargesResponseBody Body;
        
        public UpdateHSRPChargesResponse() {
        }
        
        public UpdateHSRPChargesResponse(HSRP.TSHSRPService.UpdateHSRPChargesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPChargesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateHSRPChargesResult;
        
        public UpdateHSRPChargesResponseBody() {
        }
        
        public UpdateHSRPChargesResponseBody(string UpdateHSRPChargesResult) {
            this.UpdateHSRPChargesResult = UpdateHSRPChargesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPLaserCodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPLaserCodes", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.UpdateHSRPLaserCodesRequestBody Body;
        
        public UpdateHSRPLaserCodesRequest() {
        }
        
        public UpdateHSRPLaserCodesRequest(HSRP.TSHSRPService.UpdateHSRPLaserCodesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPLaserCodesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Frontlasercode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Rearlasercode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Embossingdate;
        
        public UpdateHSRPLaserCodesRequestBody() {
        }
        
        public UpdateHSRPLaserCodesRequestBody(string Authno, string Frontlasercode, string Rearlasercode, string Embossingdate) {
            this.Authno = Authno;
            this.Frontlasercode = Frontlasercode;
            this.Rearlasercode = Rearlasercode;
            this.Embossingdate = Embossingdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPLaserCodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPLaserCodesResponse", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.UpdateHSRPLaserCodesResponseBody Body;
        
        public UpdateHSRPLaserCodesResponse() {
        }
        
        public UpdateHSRPLaserCodesResponse(HSRP.TSHSRPService.UpdateHSRPLaserCodesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPLaserCodesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateHSRPLaserCodesResult;
        
        public UpdateHSRPLaserCodesResponseBody() {
        }
        
        public UpdateHSRPLaserCodesResponseBody(string UpdateHSRPLaserCodesResult) {
            this.UpdateHSRPLaserCodesResult = UpdateHSRPLaserCodesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPAffixationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPAffixation", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.UpdateHSRPAffixationRequestBody Body;
        
        public UpdateHSRPAffixationRequest() {
        }
        
        public UpdateHSRPAffixationRequest(HSRP.TSHSRPService.UpdateHSRPAffixationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPAffixationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Affixationdate;
        
        public UpdateHSRPAffixationRequestBody() {
        }
        
        public UpdateHSRPAffixationRequestBody(string Authno, string Affixationdate) {
            this.Authno = Authno;
            this.Affixationdate = Affixationdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPAffixationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPAffixationResponse", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.UpdateHSRPAffixationResponseBody Body;
        
        public UpdateHSRPAffixationResponse() {
        }
        
        public UpdateHSRPAffixationResponse(HSRP.TSHSRPService.UpdateHSRPAffixationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPAffixationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateHSRPAffixationResult;
        
        public UpdateHSRPAffixationResponseBody() {
        }
        
        public UpdateHSRPAffixationResponseBody(string UpdateHSRPAffixationResult) {
            this.UpdateHSRPAffixationResult = UpdateHSRPAffixationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPAvailableAtOfficeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPAvailableAtOffice", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.UpdateHSRPAvailableAtOfficeRequestBody Body;
        
        public UpdateHSRPAvailableAtOfficeRequest() {
        }
        
        public UpdateHSRPAvailableAtOfficeRequest(HSRP.TSHSRPService.UpdateHSRPAvailableAtOfficeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPAvailableAtOfficeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PlateAvailableatOfficeDate;
        
        public UpdateHSRPAvailableAtOfficeRequestBody() {
        }
        
        public UpdateHSRPAvailableAtOfficeRequestBody(string Authno, string PlateAvailableatOfficeDate) {
            this.Authno = Authno;
            this.PlateAvailableatOfficeDate = PlateAvailableatOfficeDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPAvailableAtOfficeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPAvailableAtOfficeResponse", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.UpdateHSRPAvailableAtOfficeResponseBody Body;
        
        public UpdateHSRPAvailableAtOfficeResponse() {
        }
        
        public UpdateHSRPAvailableAtOfficeResponse(HSRP.TSHSRPService.UpdateHSRPAvailableAtOfficeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPAvailableAtOfficeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateHSRPAvailableAtOfficeResult;
        
        public UpdateHSRPAvailableAtOfficeResponseBody() {
        }
        
        public UpdateHSRPAvailableAtOfficeResponseBody(string UpdateHSRPAvailableAtOfficeResult) {
            this.UpdateHSRPAvailableAtOfficeResult = UpdateHSRPAvailableAtOfficeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRegnOnAuthorizationDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRegnOnAuthorizationDate", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.UpdateRegnOnAuthorizationDateRequestBody Body;
        
        public UpdateRegnOnAuthorizationDateRequest() {
        }
        
        public UpdateRegnOnAuthorizationDateRequest(HSRP.TSHSRPService.UpdateRegnOnAuthorizationDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRegnOnAuthorizationDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        public UpdateRegnOnAuthorizationDateRequestBody() {
        }
        
        public UpdateRegnOnAuthorizationDateRequestBody(string date) {
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRegnOnAuthorizationDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRegnOnAuthorizationDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.UpdateRegnOnAuthorizationDateResponseBody Body;
        
        public UpdateRegnOnAuthorizationDateResponse() {
        }
        
        public UpdateRegnOnAuthorizationDateResponse(HSRP.TSHSRPService.UpdateRegnOnAuthorizationDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateRegnOnAuthorizationDateResponseBody {
        
        public UpdateRegnOnAuthorizationDateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorizationnotRegisteredRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthorizationnotRegistered", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.GetAuthorizationnotRegisteredRequestBody Body;
        
        public GetAuthorizationnotRegisteredRequest() {
        }
        
        public GetAuthorizationnotRegisteredRequest(HSRP.TSHSRPService.GetAuthorizationnotRegisteredRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAuthorizationnotRegisteredRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fromdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string todate;
        
        public GetAuthorizationnotRegisteredRequestBody() {
        }
        
        public GetAuthorizationnotRegisteredRequestBody(string fromdate, string todate) {
            this.fromdate = fromdate;
            this.todate = todate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorizationnotRegisteredResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthorizationnotRegisteredResponse", Namespace="http://tempuri.org/", Order=0)]
        public HSRP.TSHSRPService.GetAuthorizationnotRegisteredResponseBody Body;
        
        public GetAuthorizationnotRegisteredResponse() {
        }
        
        public GetAuthorizationnotRegisteredResponse(HSRP.TSHSRPService.GetAuthorizationnotRegisteredResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAuthorizationnotRegisteredResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAuthorizationnotRegisteredResult;
        
        public GetAuthorizationnotRegisteredResponseBody() {
        }
        
        public GetAuthorizationnotRegisteredResponseBody(string GetAuthorizationnotRegisteredResult) {
            this.GetAuthorizationnotRegisteredResult = GetAuthorizationnotRegisteredResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HSRPAuthorizationServiceSoapChannel : HSRP.TSHSRPService.HSRPAuthorizationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HSRPAuthorizationServiceSoapClient : System.ServiceModel.ClientBase<HSRP.TSHSRPService.HSRPAuthorizationServiceSoap>, HSRP.TSHSRPService.HSRPAuthorizationServiceSoap {
        
        public HSRPAuthorizationServiceSoapClient() {
        }
        
        public HSRPAuthorizationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HSRPAuthorizationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HSRPAuthorizationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HSRPAuthorizationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSRP.TSHSRPService.GetHSRPAuthorizationDetailsResponse HSRP.TSHSRPService.HSRPAuthorizationServiceSoap.GetHSRPAuthorizationDetails(HSRP.TSHSRPService.GetHSRPAuthorizationDetailsRequest request) {
            return base.Channel.GetHSRPAuthorizationDetails(request);
        }
        
        public string GetHSRPAuthorizationDetails(string fromdate, string todate, string officecode) {
            HSRP.TSHSRPService.GetHSRPAuthorizationDetailsRequest inValue = new HSRP.TSHSRPService.GetHSRPAuthorizationDetailsRequest();
            inValue.Body = new HSRP.TSHSRPService.GetHSRPAuthorizationDetailsRequestBody();
            inValue.Body.fromdate = fromdate;
            inValue.Body.todate = todate;
            inValue.Body.officecode = officecode;
            HSRP.TSHSRPService.GetHSRPAuthorizationDetailsResponse retVal = ((HSRP.TSHSRPService.HSRPAuthorizationServiceSoap)(this)).GetHSRPAuthorizationDetails(inValue);
            return retVal.Body.GetHSRPAuthorizationDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSRP.TSHSRPService.GetHSRPAuthorizationnoResponse HSRP.TSHSRPService.HSRPAuthorizationServiceSoap.GetHSRPAuthorizationno(HSRP.TSHSRPService.GetHSRPAuthorizationnoRequest request) {
            return base.Channel.GetHSRPAuthorizationno(request);
        }
        
        public string GetHSRPAuthorizationno(string Authno) {
            HSRP.TSHSRPService.GetHSRPAuthorizationnoRequest inValue = new HSRP.TSHSRPService.GetHSRPAuthorizationnoRequest();
            inValue.Body = new HSRP.TSHSRPService.GetHSRPAuthorizationnoRequestBody();
            inValue.Body.Authno = Authno;
            HSRP.TSHSRPService.GetHSRPAuthorizationnoResponse retVal = ((HSRP.TSHSRPService.HSRPAuthorizationServiceSoap)(this)).GetHSRPAuthorizationno(inValue);
            return retVal.Body.GetHSRPAuthorizationnoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSRP.TSHSRPService.UpdateHSRPChargesResponse HSRP.TSHSRPService.HSRPAuthorizationServiceSoap.UpdateHSRPCharges(HSRP.TSHSRPService.UpdateHSRPChargesRequest request) {
            return base.Channel.UpdateHSRPCharges(request);
        }
        
        public string UpdateHSRPCharges(string Authno, decimal Amount, string CollectionDate) {
            HSRP.TSHSRPService.UpdateHSRPChargesRequest inValue = new HSRP.TSHSRPService.UpdateHSRPChargesRequest();
            inValue.Body = new HSRP.TSHSRPService.UpdateHSRPChargesRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.Amount = Amount;
            inValue.Body.CollectionDate = CollectionDate;
            HSRP.TSHSRPService.UpdateHSRPChargesResponse retVal = ((HSRP.TSHSRPService.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPCharges(inValue);
            return retVal.Body.UpdateHSRPChargesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSRP.TSHSRPService.UpdateHSRPLaserCodesResponse HSRP.TSHSRPService.HSRPAuthorizationServiceSoap.UpdateHSRPLaserCodes(HSRP.TSHSRPService.UpdateHSRPLaserCodesRequest request) {
            return base.Channel.UpdateHSRPLaserCodes(request);
        }
        
        public string UpdateHSRPLaserCodes(string Authno, string Frontlasercode, string Rearlasercode, string Embossingdate) {
            HSRP.TSHSRPService.UpdateHSRPLaserCodesRequest inValue = new HSRP.TSHSRPService.UpdateHSRPLaserCodesRequest();
            inValue.Body = new HSRP.TSHSRPService.UpdateHSRPLaserCodesRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.Frontlasercode = Frontlasercode;
            inValue.Body.Rearlasercode = Rearlasercode;
            inValue.Body.Embossingdate = Embossingdate;
            HSRP.TSHSRPService.UpdateHSRPLaserCodesResponse retVal = ((HSRP.TSHSRPService.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPLaserCodes(inValue);
            return retVal.Body.UpdateHSRPLaserCodesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSRP.TSHSRPService.UpdateHSRPAffixationResponse HSRP.TSHSRPService.HSRPAuthorizationServiceSoap.UpdateHSRPAffixation(HSRP.TSHSRPService.UpdateHSRPAffixationRequest request) {
            return base.Channel.UpdateHSRPAffixation(request);
        }
        
        public string UpdateHSRPAffixation(string Authno, string Affixationdate) {
            HSRP.TSHSRPService.UpdateHSRPAffixationRequest inValue = new HSRP.TSHSRPService.UpdateHSRPAffixationRequest();
            inValue.Body = new HSRP.TSHSRPService.UpdateHSRPAffixationRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.Affixationdate = Affixationdate;
            HSRP.TSHSRPService.UpdateHSRPAffixationResponse retVal = ((HSRP.TSHSRPService.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPAffixation(inValue);
            return retVal.Body.UpdateHSRPAffixationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSRP.TSHSRPService.UpdateHSRPAvailableAtOfficeResponse HSRP.TSHSRPService.HSRPAuthorizationServiceSoap.UpdateHSRPAvailableAtOffice(HSRP.TSHSRPService.UpdateHSRPAvailableAtOfficeRequest request) {
            return base.Channel.UpdateHSRPAvailableAtOffice(request);
        }
        
        public string UpdateHSRPAvailableAtOffice(string Authno, string PlateAvailableatOfficeDate) {
            HSRP.TSHSRPService.UpdateHSRPAvailableAtOfficeRequest inValue = new HSRP.TSHSRPService.UpdateHSRPAvailableAtOfficeRequest();
            inValue.Body = new HSRP.TSHSRPService.UpdateHSRPAvailableAtOfficeRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.PlateAvailableatOfficeDate = PlateAvailableatOfficeDate;
            HSRP.TSHSRPService.UpdateHSRPAvailableAtOfficeResponse retVal = ((HSRP.TSHSRPService.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPAvailableAtOffice(inValue);
            return retVal.Body.UpdateHSRPAvailableAtOfficeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSRP.TSHSRPService.UpdateRegnOnAuthorizationDateResponse HSRP.TSHSRPService.HSRPAuthorizationServiceSoap.UpdateRegnOnAuthorizationDate(HSRP.TSHSRPService.UpdateRegnOnAuthorizationDateRequest request) {
            return base.Channel.UpdateRegnOnAuthorizationDate(request);
        }
        
        public void UpdateRegnOnAuthorizationDate(string date) {
            HSRP.TSHSRPService.UpdateRegnOnAuthorizationDateRequest inValue = new HSRP.TSHSRPService.UpdateRegnOnAuthorizationDateRequest();
            inValue.Body = new HSRP.TSHSRPService.UpdateRegnOnAuthorizationDateRequestBody();
            inValue.Body.date = date;
            HSRP.TSHSRPService.UpdateRegnOnAuthorizationDateResponse retVal = ((HSRP.TSHSRPService.HSRPAuthorizationServiceSoap)(this)).UpdateRegnOnAuthorizationDate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSRP.TSHSRPService.GetAuthorizationnotRegisteredResponse HSRP.TSHSRPService.HSRPAuthorizationServiceSoap.GetAuthorizationnotRegistered(HSRP.TSHSRPService.GetAuthorizationnotRegisteredRequest request) {
            return base.Channel.GetAuthorizationnotRegistered(request);
        }
        
        public string GetAuthorizationnotRegistered(string fromdate, string todate) {
            HSRP.TSHSRPService.GetAuthorizationnotRegisteredRequest inValue = new HSRP.TSHSRPService.GetAuthorizationnotRegisteredRequest();
            inValue.Body = new HSRP.TSHSRPService.GetAuthorizationnotRegisteredRequestBody();
            inValue.Body.fromdate = fromdate;
            inValue.Body.todate = todate;
            HSRP.TSHSRPService.GetAuthorizationnotRegisteredResponse retVal = ((HSRP.TSHSRPService.HSRPAuthorizationServiceSoap)(this)).GetAuthorizationnotRegistered(inValue);
            return retVal.Body.GetAuthorizationnotRegisteredResult;
        }
    }
}
